name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2
      # step
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 2: Set up JDK 17 for building the project
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the JAR file using Gradle
      - name: Build with Gradle
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://iss-practice-module.cjq2w0cwqb5h.ap-southeast-1.rds.amazonaws.com:3306/HEALTHYRECIPY
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: ./gradlew clean build

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 6: Build and push multi-architecture Docker image
      - name: Build and push Docker image to ECR
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest-UserService \
            --push .